{"name": "测试数据：【 1532341，111111a，{except_result}，10000，token】", "status": "broken", "statusDetails": {"message": "AttributeError: 'ResultBase' object has no attribute 'response'", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x000001967E9DC390>\nusername = '1532341', password = '111111a', login_type = 1, except_code = 10000\nexcept_msg = 'token'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, login_type, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, login_type, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password, login_type)\n        step_1(username)\n>       assert result.response.status_code == 1000\nE       AttributeError: 'ResultBase' object has no attribute 'response'\n\ntest_03_login.py:30: AttributeError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'1532341'"}], "start": 1669186340609, "stop": 1669186340609}], "attachments": [{"name": "log", "source": "dba414bc-89d8-4b51-864b-e7fb6ffbc95d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'1532341'"}, {"name": "password", "value": "'111111a'"}, {"name": "login_type", "value": "1"}, {"name": "except_code", "value": "10000"}, {"name": "except_msg", "value": "'token'"}], "start": 1669186340094, "stop": 1669186340610, "uuid": "56c4d73d-f3e1-4669-bd63-8785c8ea4239", "historyId": "fc744133cd1f19c331d93737caf7e646", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "feature", "value": "用户登录模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "用例--登录用户"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "lijuan"}, {"name": "thread", "value": "21704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}